# PLEASE STOP!
# DO NOT EDIT THIS FILE OR DELETE THIS FILE
# Create a new config.py in the same directory and extend this class.

import os
from typing import Set


class ConfigMeta(type):
    """Metaclass to provide default empty string for missing Config attributes"""
    def __getattr__(cls, name):
        # Return empty list for known collection types to avoid iteration errors
        if name in ["NO_LOAD", "SUDO_USERS", "BL_CHATS", "SUDO_COMMANDS"]:
            return []
        return ""

class Config(metaclass=ConfigMeta):
    # --- CORE BOT SETTINGS ---
    LOGGER = True
    ALIVE_NAME = os.environ.get("ALIVE_NAME", "CatUserbot")
    APP_ID = int(os.environ.get("APP_ID") or 0)
    API_HASH = os.environ.get("API_HASH", None)
    STRING_SESSION = os.environ.get("STRING_SESSION", None)

    # --- ASSISTANT BOT SETTINGS ---
    TG_BOT_TOKEN = os.environ.get("TG_BOT_TOKEN", None)
    TG_BOT_USERNAME = os.environ.get("TG_BOT_USERNAME", None)

    # --- DATABASE & PERSISTENCE ---
    DB_URI = os.environ.get("DATABASE_URL", None)
    CACHE_PATH = os.environ.get("CACHE_PATH", "./userbot/cache/")

    # --- LOGGING & PERMIT ---
    PRIVATE_GROUP_BOT_API_ID = int(os.environ.get("PRIVATE_GROUP_BOT_API_ID") or 0)
    PM_LOGGER_GROUP_ID = int(os.environ.get("PM_LOGGER_GROUP_ID") or 0)
    OWNER_ID = int(os.environ.get("OWNER_ID") or 0)

    # --- CUSTOMIZATION ---
    COMMAND_HAND_LER = os.environ.get("COMMAND_HAND_LER", r".")
    SUDO_COMMAND_HAND_LER = os.environ.get("SUDO_COMMAND_HAND_LER", r".")
    TZ = os.environ.get("TZ", "Asia/Kolkata")
    THUMB_IMAGE = os.environ.get(
        "THUMB_IMAGE", "https://graph.org/file/ca95524e4734b0d5461b5.jpg"
    )

    # --- UPSTREAM & PLUGINS ---
    UPSTREAM_REPO = os.environ.get(
        "UPSTREAM_REPO", "https://github.com/itswill00/catuserbot"
    )
    UPSTREAM_REPO_BRANCH = os.environ.get("UPSTREAM_REPO_BRANCH", "master")
    EXTERNAL_REPO = os.environ.get("EXTERNAL_REPO", None)
    PLUGIN_CHANNEL = int(os.environ.get("PLUGIN_CHANNEL") or 0)
    NO_LOAD = list(os.environ.get("NO_LOAD", "").split())

    # --- PLUGIN SPECIFIC ---
    FBAN_GROUP_ID = int(os.environ.get("FBAN_GROUP_ID") or 0)
    FINISHED_PROGRESS_STR = os.environ.get("FINISHED_PROGRESS_STR", "█")
    UNFINISHED_PROGRESS_STR = os.environ.get("UNFINISHED_PROGRESS_STR", "░")
    G_DRIVE_CLIENT_ID = os.environ.get("G_DRIVE_CLIENT_ID", None)
    G_DRIVE_CLIENT_SECRET = os.environ.get("G_DRIVE_CLIENT_SECRET", None)

    # --- EXTERNAL API KEYS ---
    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", None)
    SPAMWATCH_API = os.environ.get("SPAMWATCH_API", None)
    GENIUS_API_TOKEN = os.environ.get("GENIUS_API_TOKEN", None)

    # --- HEROKU SETTINGS ---
    HEROKU_API_KEY = os.environ.get("HEROKU_API_KEY", None)
    HEROKU_APP_NAME = os.environ.get("HEROKU_APP_NAME", None)

    # --- SYSTEM PATHS ---
    TMP_DOWNLOAD_DIRECTORY = os.environ.get("TMP_DOWNLOAD_DIRECTORY", "./downloads/")
    TEMP_DIR = os.environ.get("TEMP_DIR", "./temp/")

    # --- DO NOT EDIT BELOW ---
    MAX_MESSAGE_SIZE_LIMIT = 4095
    SUDO_USERS: Set[int] = set()
    CATUBLOGO = None
    BOTLOG = False
    BOTLOG_CHATID = 0

class Production(Config):
    LOGGER = False

class Development(Config):
    LOGGER = True
