# PLEASE STOP!
# DO NOT EDIT THIS FILE OR DELETE THIS FILE
# Create a new config.py file in same directory and import, then extend this class.

import os
from typing import Set
from telethon.tl.types import ChatBannedRights
from validators.url import url

class Config(object):
    # --- CORE BOT SETTINGS ---
    LOGGER = True
    ALIVE_NAME = os.environ.get("ALIVE_NAME", "CatUserbot")
    APP_ID = int(os.environ.get("APP_ID", 0)) # Get from my.telegram.org
    API_HASH = os.environ.get("API_HASH", None) # Get from my.telegram.org
    STRING_SESSION = os.environ.get("STRING_SESSION", None)
    
    # --- ASSISTANT BOT SETTINGS ---
    TG_BOT_TOKEN = os.environ.get("TG_BOT_TOKEN", None)
    TG_BOT_USERNAME = os.environ.get("TG_BOT_USERNAME", None)
    
    # --- DATABASE & PERSISTENCE ---
    DB_URI = os.environ.get("DATABASE_URL", None)
    # Local cache directory for JSON DB files
    CACHE_PATH = os.environ.get("CACHE_PATH", "./userbot/cache/")
    
    # --- LOGGING & PERMIT ---
    # PRIVATE_GROUP_BOT_API_ID is required for logging errors and startup
    PRIVATE_GROUP_BOT_API_ID = int(os.environ.get("PRIVATE_GROUP_BOT_API_ID", 0))
    # Set same as above if you want PM logs to go to the same group
    PM_LOGGER_GROUP_ID = int(os.environ.get("PM_LOGGER_GROUP_ID", 0))
    OWNER_ID = int(os.environ.get("OWNER_ID", 0))
    
    # --- CUSTOMIZATION ---
    COMMAND_HAND_LER = os.environ.get("COMMAND_HAND_LER", r".")
    SUDO_COMMAND_HAND_LER = os.environ.get("SUDO_COMMAND_HAND_LER", r".")
    TZ = os.environ.get("TZ", "Asia/Kolkata")
    THUMB_IMAGE = os.environ.get("THUMB_IMAGE", "https://graph.org/file/ca95524e4734b0d5461b5.jpg")
    
    # --- UPSTREAM & PLUGINS ---
    UPSTREAM_REPO = os.environ.get("UPSTREAM_REPO", "https://github.com/itswill00/catuserbot")
    UPSTREAM_REPO_BRANCH = os.environ.get("UPSTREAM_REPO_BRANCH", "master")
    EXTERNAL_REPO = os.environ.get("EXTERNAL_REPO", None)
    NO_LOAD = list(os.environ.get("NO_LOAD", "").split())
    
    # --- EXTERNAL API KEYS ---
    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", None)
    SPAMWATCH_API = os.environ.get("SPAMWATCH_API", None)
    GENIUS_API_TOKEN = os.environ.get("GENIUS_API_TOKEN", None)
    OCR_SPACE_API_KEY = os.environ.get("OCR_SPACE_API_KEY", None)
    REM_BG_API_KEY = os.environ.get("REM_BG_API_KEY", None)
    
    # --- SYSTEM PATHS ---
    TMP_DOWNLOAD_DIRECTORY = os.environ.get("TMP_DOWNLOAD_DIRECTORY", "./downloads/")
    TEMP_DIR = os.environ.get("TEMP_DIR", "./temp/")
    
    # --- DO NOT EDIT BELOW ---
    MAX_MESSAGE_SIZE_LIMIT = 4095
    SUDO_USERS: Set[int] = set()
    CATUBLOGO = None
    BOTLOG = False
    BOTLOG_CHATID = 0

class Production(Config):
    LOGGER = False

class Development(Config):
    LOGGER = True
